services:
  - type: web
    plan: free
    name: drf-jwt-tutorial-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn drf_jwt_turorial_be.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: DATABASE_TYPE
        value: sqlite
