services:
  - type: web
    plan: free
    name: drf-jwt-tutorial-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn drf_jwt_turorial_be.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: drf_jwt_tutorial_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false

databases:
  - name: drf_jwt_tutorial_db
    databaseName: drf_jwt_tutorial
    user: drf_jwt_tutorial_user
    plan: free
